name: build-and-test
on: [push]
jobs:
  check-code-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Check Pom Sort
        run: mvn -B sortpom:verify
      - name: Check File Formatting
        run: mvn -B fmt:check
      - name: Test Code
        run: mvn -B verify